services:
  - type: web
    name: sra-data-processing
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: pro
    region: oregon
    branch: fundata-seeding
    rootDir: .
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80
    shutdownDelaySeconds: 300
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: ENVIRONMENT
        value: production
      - key: FUNDATA_DATA_PATH
        value: fundata/data
      - key: FUNDATA_QUOTES_PATH
        value: fundata/quotes
      - key: ENABLE_METRICS
        value: true
      - key: HEALTH_CHECK_INTERVAL
        value: 60