services:
  - type: background-worker
    name: sra-data-processing
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    region: oregon
    branch: fundata-seeding
    rootDir: .
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: ENVIRONMENT
        value: production
      - key: FUNDATA_DATA_PATH
        value: fundata/data
      - key: FUNDATA_QUOTES_PATH
        value: fundata/quotes
      - key: ENABLE_METRICS
        value: true
      - key: HEALTH_CHECK_INTERVAL
        value: 60